import type { Binding } from "./spine";

export const GENRES = [
  "Fiction",
  "Nonfiction",
  "Sci-Fi",
  "Fantasy",
  "Mystery & Thrillers",
  "Romance",
] as const;

export type Genre = (typeof GENRES)[number];

export type Book = {
  id: string;
  title: string;
  author: string;
  /** Drives spine width via the PPI formula. */
  pages: number;
  /** Drives spine height. */
  binding: Binding;
  genre: Genre;
  /**
   * Sampled from the cover art. Hand-picked for now — this is the field
   * node-vibrant fills in once covers are being fetched.
   */
  color: string;
  year: number;
  rating: number;
  note: string;
};

export const BOOKS: Book[] = [
  {
    id: "piranesi",
    title: "Piranesi",
    author: "Susanna Clarke",
    pages: 272,
    binding: "trade",
    genre: "Fantasy",
    color: "#2A6068",
    year: 2020,
    rating: 5,
    note: "A house of endless halls and tides. Read it in two sittings and immediately started again.",
  },
  {
    id: "secret-history",
    title: "The Secret History",
    author: "Donna Tartt",
    pages: 559,
    binding: "trade",
    genre: "Mystery & Thrillers",
    color: "#1B2A20",
    year: 1992,
    rating: 5,
    note: "You know who dies on the first page. It still ruins you.",
  },
  {
    id: "normal-people",
    title: "Normal People",
    author: "Sally Rooney",
    pages: 266,
    binding: "trade",
    genre: "Fiction",
    color: "#93AEC1",
    year: 2018,
    rating: 4,
    note: "Two people repeatedly failing to say the obvious thing.",
  },
  {
    id: "circe",
    title: "Circe",
    author: "Madeline Miller",
    pages: 393,
    binding: "hardcover",
    genre: "Fantasy",
    color: "#C2662B",
    year: 2018,
    rating: 5,
    note: "A witch gets a thousand years to figure out what she wants.",
  },
  {
    id: "klara",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    pages: 303,
    binding: "hardcover",
    genre: "Fiction",
    color: "#E3C86A",
    year: 2021,
    rating: 4,
    note: "Narrated by a solar-powered robot who loves too well.",
  },
  {
    id: "song-of-achilles",
    title: "The Song of Achilles",
    author: "Madeline Miller",
    pages: 352,
    binding: "trade",
    genre: "Fantasy",
    color: "#27406B",
    year: 2011,
    rating: 5,
    note: "Everyone told me how it ends. Did not help.",
  },
  {
    id: "tomorrow",
    title: "Tomorrow, and Tomorrow, and Tomorrow",
    author: "Gabrielle Zevin",
    pages: 401,
    binding: "hardcover",
    genre: "Fiction",
    color: "#2E4272",
    year: 2022,
    rating: 4,
    note: "Thirty years of making games together, and never once saying it.",
  },
  {
    id: "a-little-life",
    title: "A Little Life",
    author: "Hanya Yanagihara",
    pages: 720,
    binding: "trade",
    genre: "Fiction",
    color: "#6B6660",
    year: 2015,
    rating: 4,
    note: "Do not start this one on a weeknight.",
  },
  {
    id: "beloved",
    title: "Beloved",
    author: "Toni Morrison",
    pages: 324,
    binding: "trade",
    genre: "Fiction",
    color: "#8E3B33",
    year: 1987,
    rating: 5,
    note: "A house haunted by what was done to the people in it.",
  },
  {
    id: "jonathan-strange",
    title: "Jonathan Strange & Mr Norrell",
    author: "Susanna Clarke",
    pages: 1006,
    binding: "trade",
    genre: "Fantasy",
    color: "#1C1A17",
    year: 2004,
    rating: 5,
    note: "English magic, restored, with footnotes. Worth every one of its thousand pages.",
  },
  {
    id: "the-idiot",
    title: "The Idiot",
    author: "Elif Batuman",
    pages: 423,
    binding: "trade",
    genre: "Fiction",
    color: "#E0D3B8",
    year: 2017,
    rating: 4,
    note: "Email, linguistics, and being nineteen and wrong about everything.",
  },
  {
    id: "educated",
    title: "Educated",
    author: "Tara Westover",
    pages: 352,
    binding: "hardcover",
    genre: "Nonfiction",
    color: "#B9C9D3",
    year: 2018,
    rating: 5,
    note: "Seventeen before she set foot in a classroom.",
  },
  {
    id: "bunny",
    title: "Bunny",
    author: "Mona Awad",
    pages: 305,
    binding: "trade",
    genre: "Fiction",
    color: "#D287A6",
    year: 2019,
    rating: 4,
    note: "An MFA cohort with a very literal workshop process.",
  },
  {
    id: "never-let-me-go",
    title: "Never Let Me Go",
    author: "Kazuo Ishiguro",
    pages: 288,
    binding: "massMarket",
    genre: "Sci-Fi",
    color: "#35786F",
    year: 2005,
    rating: 5,
    note: "The horror arrives quietly, several chapters after you worked it out.",
  },
  {
    id: "project-hail-mary",
    title: "Project Hail Mary",
    author: "Andy Weir",
    pages: 476,
    binding: "hardcover",
    genre: "Sci-Fi",
    color: "#1E2A44",
    year: 2021,
    rating: 4,
    note: "Man wakes up alone on a spaceship. Solves problems. Delightful.",
  },
  {
    id: "left-hand",
    title: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    pages: 304,
    binding: "massMarket",
    genre: "Sci-Fi",
    color: "#4A3B6B",
    year: 1969,
    rating: 5,
    note: "The long walk across the ice is the best thing in the genre.",
  },
  {
    id: "station-eleven",
    title: "Station Eleven",
    author: "Emily St. John Mandel",
    pages: 333,
    binding: "trade",
    genre: "Sci-Fi",
    color: "#2F5E5A",
    year: 2014,
    rating: 5,
    note: "Because survival is insufficient.",
  },
  {
    id: "braiding-sweetgrass",
    title: "Braiding Sweetgrass",
    author: "Robin Wall Kimmerer",
    pages: 391,
    binding: "trade",
    genre: "Nonfiction",
    color: "#7A8B5C",
    year: 2013,
    rating: 5,
    note: "Botany and reciprocity. Read a chapter at a time.",
  },
  {
    id: "sapiens",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    pages: 443,
    binding: "trade",
    genre: "Nonfiction",
    color: "#D9CDBB",
    year: 2011,
    rating: 3,
    note: "Confident about a great many things.",
  },
  {
    id: "magical-thinking",
    title: "The Year of Magical Thinking",
    author: "Joan Didion",
    pages: 227,
    binding: "trade",
    genre: "Nonfiction",
    color: "#2B2B2B",
    year: 2005,
    rating: 5,
    note: "Grief, documented with the precision of a reporter.",
  },
  {
    id: "just-kids",
    title: "Just Kids",
    author: "Patti Smith",
    pages: 304,
    binding: "trade",
    genre: "Nonfiction",
    color: "#C9BBA8",
    year: 2010,
    rating: 5,
    note: "Two broke artists at the Chelsea Hotel, promising to keep each other going.",
  },
  {
    id: "h-is-for-hawk",
    title: "H is for Hawk",
    author: "Helen Macdonald",
    pages: 300,
    binding: "trade",
    genre: "Nonfiction",
    color: "#8A5B33",
    year: 2014,
    rating: 4,
    note: "A grieving woman trains a goshawk. It goes about as well as that sounds.",
  },
  {
    id: "priory",
    title: "The Priory of the Orange Tree",
    author: "Samantha Shannon",
    pages: 848,
    binding: "hardcover",
    genre: "Fantasy",
    color: "#7B3A52",
    year: 2019,
    rating: 4,
    note: "Dragons, on both sides of a very long argument.",
  },
  {
    id: "castle",
    title: "We Have Always Lived in the Castle",
    author: "Shirley Jackson",
    pages: 214,
    binding: "trade",
    genre: "Mystery & Thrillers",
    color: "#A8483F",
    year: 1962,
    rating: 5,
    note: "Merricat, said Connie, would you like a cup of tea?",
  },
  {
    id: "gone-girl",
    title: "Gone Girl",
    author: "Gillian Flynn",
    pages: 415,
    binding: "trade",
    genre: "Mystery & Thrillers",
    color: "#3A3E42",
    year: 2012,
    rating: 4,
    note: "The diary section is a magic trick.",
  },
  {
    id: "silent-patient",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    pages: 336,
    binding: "trade",
    genre: "Mystery & Thrillers",
    color: "#B0655F",
    year: 2019,
    rating: 3,
    note: "Guessed it at page 200 and still turned every page.",
  },
  {
    id: "small-things",
    title: "Small Things Like These",
    author: "Claire Keegan",
    pages: 128,
    binding: "hardcover",
    genre: "Fiction",
    color: "#4A5D4E",
    year: 2021,
    rating: 5,
    note: "A hundred and twenty pages and not one of them wasted.",
  },
  {
    id: "beach-read",
    title: "Beach Read",
    author: "Emily Henry",
    pages: 361,
    binding: "trade",
    genre: "Romance",
    color: "#E4A0A8",
    year: 2020,
    rating: 4,
    note: "Two blocked writers swap genres for a summer.",
  },
  {
    id: "people-we-meet",
    title: "People We Meet on Vacation",
    author: "Emily Henry",
    pages: 364,
    binding: "trade",
    genre: "Romance",
    color: "#EBB394",
    year: 2021,
    rating: 4,
    note: "Ten summers, one ruined friendship, and an attempt to fix it.",
  },
];
